# Generated by Django 5.2.4 on 2025-08-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carzApis', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
