# Generated by Django 5.2.4 on 2025-08-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzApis', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
