# Generated by Django 5.2.4 on 2025-08-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzApis', '0004_usermodle'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodle',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
