# Generated by Django 5.2.4 on 2025-08-28 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_user_bookingmodel_user_id'),
        ('carzApis', '0005_usermodle_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModle',
            new_name='UserModel',
        ),
    ]
