# Generated by Django 5.2.4 on 2025-08-27 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('carzApis', '0005_usermodle_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carzApis.usermodle'),
        ),
    ]
