# Generated by Django 5.2.4 on 2025-08-27 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_bookingmodel_user_id'),
        ('carzApis', '0005_usermodle_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='carzApis.usermodle'),
        ),
    ]
