# Generated by Django 5.2.4 on 2025-08-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_bookingmodel_user_id_bookingmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingmodel',
            old_name='car_id',
            new_name='car',
        ),
    ]
