# Generated by Django 5.2.4 on 2025-08-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_rename_car_id_bookingmodel_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
