# Generated by Django 5.2.4 on 2025-08-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_bookingmodel_date_alter_bookingmodel_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='car',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='time',
        ),
    ]
