# Generated by Django 5.2.4 on 2025-08-28 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_bookingmodel_address_remove_bookingmodel_car_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingmodel',
            old_name='user',
            new_name='user_id',
        ),
    ]
