# Generated by Django 5.2.4 on 2025-08-28 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_user_bookingmodel_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingmodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
