# Generated by Django 5.2.4 on 2025-08-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_rename_user_id_bookingmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='address',
            field=models.CharField(default='dfas', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='card_number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
