# Generated by Django 5.2.4 on 2025-08-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_bookingmodel_address_bookingmodel_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='car',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
