# Generated by Django 5.2.4 on 2025-09-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_bookingmodel_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='date',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='time',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
