# Generated by Django 5.2.4 on 2025-09-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzApis', '0006_rename_usermodle_usermodel'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='carzApis.usermodel'),
        ),
    ]
