# Generated by Django 5.2.4 on 2025-09-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_addressmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmodel',
            name='user',
        ),
    ]
