# Generated by Django 5.2.4 on 2025-10-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_addressmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardHolderName', models.CharField()),
                ('last4Digits', models.IntegerField()),
                ('cardType', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('amex', 'American Express'), ('discover', 'Discover'), ('other', 'Other')], default='other')),
                ('expiryMonth', models.CharField()),
                ('expiryYear', models.CharField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
