# Generated by Django 5.2.4 on 2025-10-08 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzApis', '0006_rename_usermodle_usermodel'),
        ('user', '0007_paymentmethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='cardHolderName',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='cardType',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='expiryMonth',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='expiryYear',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='last4Digits',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card_holder_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card_type',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('amex', 'American Express'), ('discover', 'Discover'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='expiry_month',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='expiry_year',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='last4_digits',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='carzApis.usermodel'),
        ),
    ]
