# Generated by Django 5.2.4 on 2025-08-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('brand', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('transmission_options', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('is_trend', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('can_connect_bluetooth', models.BooleanField(default=False)),
                ('is_automatic', models.BooleanField(default=False)),
            ],
        ),
    ]
