# Generated by Django 5.2.4 on 2025-08-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='fuel_type',
            field=models.CharField(choices=[('pet', 'Petrol'), ('elc', 'Electric'), ('hyb', 'Hybrid'), ('dis', 'Diesel'), ('cng', 'CNG'), ('lpg', 'LPG')], default='pet', max_length=50),
        ),
    ]
