# Generated by Django 5.2.4 on 2025-08-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_carmodel_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='imgUrl',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(choices=[('toy', 'Toyota'), ('hon', 'Honda'), ('for', 'Ford'), ('bmw', 'BMW'), ('mer', 'Mercedes-Benz'), ('aud', 'Audi'), ('vw', 'Volkswagen'), ('hyu', 'Hyundai'), ('nis', 'Nissan'), ('tes', 'Tesla')], default='hyu', max_length=50),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_type',
            field=models.CharField(choices=[('eco', 'Economy'), ('sed', 'Sedan'), ('suv', 'SUV'), ('cou', 'Coupe'), ('hat', 'Hatchback'), ('con', 'Convertible'), ('pic', 'Pickup Truck'), ('van', 'Van'), ('lux', 'Luxury'), ('spo', 'Sports Car')], default='eco', max_length=50),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='transmission_options',
            field=models.CharField(choices=[('man', 'Manual'), ('aut', 'Automatic'), ('sem', 'Semi-Automatic'), ('cvt', 'CVT'), ('dct', 'Dual-Clutch Transmission')], default='aut', max_length=100),
        ),
    ]
