# Generated by Django 5.2.4 on 2025-08-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_carmodel_imgurl_alter_carmodel_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='is_trend',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='brandImage',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(choices=[('hon', 'Honda'), ('vw', 'Volkswagen'), ('bmw', 'BMW'), ('aud', 'Audi'), ('nis', 'Nissan'), ('for', 'Ford'), ('fra', 'Farrari'), ('lamb', 'Lamborghini'), ('mer', 'Mercedes'), ('tes', 'Tesla'), ('toy', 'Toyota'), ('hyu', 'Hyundai')], default='hyu', max_length=50),
        ),
    ]
