# Generated by Django 5.2.4 on 2025-08-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_carmodel_is_trend_carmodel_brandimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brandImage',
            field=models.CharField(default='', max_length=500),
        ),
    ]
