# Generated by Django 5.2.4 on 2025-08-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_carmodel_brandimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_in_database', models.CharField(max_length=100)),
                ('imag_url', models.CharField(max_length=500)),
            ],
        ),
    ]
