# Generated by Django 5.2.4 on 2025-08-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_brandmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='numbers',
            field=models.IntegerField(default=42),
        ),
    ]
