# Generated by Django 5.2.4 on 2025-08-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_brandmodel_numbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandmodel',
            old_name='imag_url',
            new_name='image_url',
        ),
    ]
