# Generated by Django 5.2.4 on 2025-10-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_imag_url_brandmodel_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(choices=[('hon', 'Honda'), ('vw', 'Volkswagen'), ('bmw', 'BMW'), ('aud', 'Audi'), ('nis', 'Nissan'), ('Ford', 'Ford'), ('Farrari', 'Farrari'), ('lamb', 'Lamborghini'), ('mer', 'Mercedes'), ('tes', 'Tesla'), ('toy', 'Toyota'), ('hyu', 'Hyundai')], default='hyu', max_length=50),
        ),
    ]
